apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: blue
  template: 
    metadata:
      labels:
        app: frontend
        version: blue
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.blue.image }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
