version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    image: adinarayan25/javakube-backend:v1
    platform: linux/amd64
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: adinarayan25/javakube-frontend:v2
    platform: linux/amd64
    ports:
      - "3000:80"
    depends_on:
      - backend
