apiVersion: v1
kind: Namespace
metadata:
  name: adityanamespace

---
# BACKEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: adityanamespace
  name: java-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: java-backend
          image: adinarayan25/javakube-backend:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
# BACKEND SERVICE
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: adityanamespace
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
# FRONTEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: adityanamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: react-frontend
          image: adinarayan25/javakube-frontend:v2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
# FRONTEND SERVICE
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: adityanamespace
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
